### ISSUE TITLE
[BUG] dressing room dummy can be completely empty

### ISSUE THREAD

**Issue by k-veikur** [Nensec/FRSkinTester#10]
**Describe the bug**
pasting an undressed mannequin image link onto the dressing room field goes through and displays the skin on the dummy without any dragon or outfit on it.

![image](https://user-images.githubusercontent.com/32003188/58128134-38c46d80-7c17-11e9-94c8-4e2bac1a2525.png)

**Contextual information**
I used a dummy image link from the dressing room.

**Comment by Nensec** [comment]
This should be fixed now
