### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bioluminosity** [Nensec/FRSkinTester#2]
**Describe the bug**
Previews do not work for dragon scries or existing dragons - the page "blinks", but does not travel to the rendered preview page; it stays on the "paste code/ID" page.

**Contextual information**
I used this dragon id: 27329804
I used this scryer image link: http://flightrising.com/rendern/350/273299/27329804_350.png?mtime=XFyEOAACqj8

**Comment by Nensec** [comment]
This should be fixed now. Sorry about that!
