### ISSUE TITLE
Discord Login Link: Oauth Invalid

### ISSUE THREAD

**Issue by TessaKTaylor** [Nensec/FRSkinTester#21]
The login via Discord link directs the user to an 'Invalid OAuth' error page within Discord's API.

**Comment by Nensec** [comment]
I just checked and it seems to work just fine for me

![chrome_2022-03-07_18-46-39](https://user-images.githubusercontent.com/672037/157089096-b9bd0892-6b40-4ef9-b02d-ebaa788b287f.gif)

Are you getting a red bar at the top of the page after you attempt to log in? If so, retrying to log in usually works. It's a known issue and I have no idea how to fix it 😞
