### ISSUE TITLE
[BUG] Can no longer access my skin manage page

### ISSUE THREAD

**Issue by kiwipen** [Nensec/FRSkinTester#3]
**Describe the bug**
Every time I go to manage my skins / go to my skin manage page, I'm greeted with the following page;
Error.
An error occurred while processing your request.

The site takes a long time to load and ultimately leads to that.

**Contextual information**
I used this dragon id: 
I used this scryer image link: I used my personal skin management link.
I can discord it to you if needed.

**Comment by Nensec** [comment]
Sorry about that, my last update broke the management page apparently. Should be fixed now!

**Comment by NoodleNox** [comment]
@Nensec I'm having the same issue on the link that says: "Hello Username!"

**Comment by Nensec** [comment]
@NoodleNox You will have to be a bit more precise, also this is a ticket that was closed 2 months ago :p

**Comment by NoodleNox** [comment]
@Nensec at the top of the FR Skin Tester page there is a link to your profile that says Hello (Username)! So, on mine it says Hello NoodleNox! 
The first few times I logged in I could view all of my skins and accents from this page without going to the management tab. Now when I click on it is says " Error. An error occurred while processing your request."

**Comment by Nensec** [comment]
@NoodleNox I think I fixed the issue (next time though, please make a new ticket ^. ^ )
