### ISSUE TITLE
Scry preview page doesn't have a profile link

### ISSUE THREAD

**Issue by k-veikur** [Nensec/FRSkinTester#7]
I opened a previewer link for scries on my skincent [here](https://frskintester.nensec.com/Preview/KzLHE/Scry) and the human icon that's supposed to lead you to your tester profile isn't there. I checked on another skin and none of the scry links have it.

![image](https://user-images.githubusercontent.com/32003188/54782504-5aa57200-4c1f-11e9-8ac8-5f3c7214fa17.png)

**Comment by Nensec** [comment]
Fixed
